<?php
class JConfig {
	var $offline = '0';
	var $editor = 'tinymce';
	var $list_limit = '100';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '0';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '100';
	var $feed_email = 'author';
	var $secret = '3uvlswM^YTYZmBVPJVMlls0rv';
	var $gzip = '0';
	var $error_reporting = '0';
	var $xmlrpc_server = '0';
	var $log_path = '/mnt/data/vhosts/lavueltaalmundosinpasta.cloudaccess.net/httpdocs/logs';
	var $tmp_path = '/mnt/data/vhosts/lavueltaalmundosinpasta.cloudaccess.net/httpdocs/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '0';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'memcache';
	var $memcache_settings = array("persistent" => "0", "compression" => "0", "servers" => array("0" => array("host" => "mem", "port" => "11211")));
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = '127.0.0.1';
	var $user = 'root';
	var $db = 'bitnami_joomla';
	var $dbprefix = 'asc_';
	var $mailer = 'mail';
	var $mailfrom = 'jorge.webservices@gmail.com';
	var $fromname = 'Administrador de Lavueltaalmundosinpasta.cloudaccess.net';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '180';
	var $session_handler = 'database';
	var $password = 'andrwn';
	var $sitename = 'La Vuelta Al Mundo Sin Pasta - Porque viajar, es sobretodo ilusión!';
	var $MetaDesc = 'La Vuelta Al Mundo Sin Pasta - Porque viajar, es sobretodo ilusión! Mira dónde';
	var $MetaKeys = 'vuelta al mundo, viajar, sueño';
	var $offline_message = 'This site is down for maintenance. Please check back again soon.';
}
?>